### ISSUE TITLE
Not working as described in tutorial

### ISSUE THREAD

**Issue by davidlinse** [gextech/grunt-nightwatch#62]
Mayeb i'm doing something wrong but it looks like that neither the `config_path` property is respected nor the `cli arguments` are correctly parsed/merged.

As in your example i've got a configuration section in the _Gruntfile.js_ which looks like:
```js
    nightwatch: {
      options: {
        config_path: './config.json',  # no effect
        globals_path: './globals.json',
        custom_commands_path: null,
        custom_assertions_path: null,
        src_folders: ['./test/nw'],
        test_settings: {

          chrome: {
            selenium_host: "127.0.0.1",
            selenium_port: 4444,
            launch_url: "",
            silent: true,
            end_session_on_fail: false,
            skip_testcases_on_fail: false,
            screenshots: {
              enabled: false,
              path: ""
            },
            desiredCapabilities: {
              browserName: "chrome",
              javascriptEnabled: true,
              acceptSslCerts: true,
              chromeOptions : {
                args : ["start-maximized"]
              }
            }
          }
        },
      },
      chrome: {
        config_path: './config.json', # no effect
        env: 'chrome'
      }
```

No matter which way i try to run the task
```
$ grunt nightwatch # or
$ grunt nightwatch:chrome #or
$ grunt nightwatch --env chrome | default
```
I always see the following error message..

```
Warning: No testing environment specified. Use --force to continue.
Error: No testing environment specified.
    at Object.CliRunner.parseTestSettings (/Users/user/forms-ui-test/node_modules/grunt-nightwatch/node_modules/nwrun/node_modules/nightwatch/lib/runner/cli/clirunner.js:458:13)
    at Object.CliRunner.setup (/Users/user/forms-ui-test/node_modules/grunt-nightwatch/node_modules/nwrun/node_modules/nightwatch/lib/runner/cli/clirunner.js:53:8)
    at Object.exports.runner (/Users/user/forms-ui-test/node_modules/grunt-nightwatch/node_modules/nwrun/node_modules/nightwatch/lib/index.js:546:17)
    at /Users/user/forms-ui-test/node_modules/grunt-nightwatch/node_modules/nwrun/lib/spawn.js:54:18
    at Object.exports.cli (/Users/user/forms-ui-test/node_modules/grunt-nightwatch/node_modules/nwrun/node_modules/nightwatch/lib/index.js:540:5)
    at spawnNightwatch (/Users/user/forms-ui-test/node_modules/grunt-nightwatch/node_modules/nwrun/lib/spawn.js:38:16)
    at runTests (/Users/user/forms-ui-test/node_modules/grunt-nightwatch/node_modules/nwrun/lib/spawn.js:72:5)
    at module.exports (/Users/user/forms-ui-test/node_modules/grunt-nightwatch/node_modules/nwrun/lib/spawn.js:100:5)
    at module.exports (/Users/user/forms-ui-test/node_modules/grunt-nightwatch/node_modules/nwrun/lib/runner.js:105:3)
    at Object.<anonymous> (/Users/user/forms-ui-test/node_modules/grunt-nightwatch/tasks/nightwatch.js:30:5)
```
The referenced `config.json` is copied and updated from a fully working project w/o `grunt-nightwatch` as dependency.

Maybe this Is this related to #19 ?
Let me know if i can provide some more infos.

kind regards
~david

**Comment by davidlinse** [comment]
Any news on this ? 

/cc @pateketrueke

**Comment by pateketrueke** [comment]
I'm looking at this, thanks for your feedback.

**Comment by pateketrueke** [comment]
Update: I've revisited this issue and seems to be working, but of course, need more clarification about how it works.

Given the following settings:

```javascript
grunt.initConfig({
  nightwatch: {
    options: {},
    some_target: {}
  }
});
```

The `config_path` key works only for targets, this means "test_settings" within `nightwatch.json` configuration.

The grunt task will treat each key of its settings (except `options`) as targets.

You'll end up with something like this:

```json
{
  "test_settings": {
    "some_target": {}
  }
}
```

The `config_path` option will work only within targets, having `{ some_target: { config_path: 'settings.json' } }` would be enough.

But no config file will be read and merged unless you execute it explicitly, e.g. `grunt nightwatch:some_target`

A working example of this behavior is within the `Gruntfile.coffee` from this repo.

Of course, your `config.json` should be fully compatible with "test_settings".
